---
- name: Converge
  become: true
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python
    pbf_url: 'http://download.geofabrik.de/russia/south-fed-district-latest.osm.pbf'
    pip_install_packages: docker
  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: aemelyanenko.osm
